### ISSUE TITLE
Docker resets to AUFS after a reboot

### ISSUE THREAD

**Issue by gourao** [portworx/lcfs#37]
After I reboot my system (ubuntu), Docker goes back to using AUFS as the driver.  Consequently I lose my previous images. 

LCFS needs to be retained across boots.

**Comment by jjobi** [comment]
These are the steps to recover docker images after reboot as of now:

1. Stop docker if running
2. Start LCFS with same device (/opt/pwx/bin/lcfs /dev/sdb /var/lib/docker /lcfs).
3.  Restart docker with lcfs.   All images/containers will be restored at this point.

Jose was saying running the command " /opt/pwx/bin/lcfs-setup.sh --start" would do the above.
This need to be taken care automatically and that work is pending.

**Comment by jjobi** [comment]
Jose added a service, which starts lcfs followed by Docker after reboot.
